<a href="https://colab.research.google.com/github/Saiful-2/forest-cover-classification/blob/main/notebooks/1_forest_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/Saiful-2/datasets/main/forest_dirty_dataset.csv"
df = pd.read_csv(url)

df.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type,Soil_Sum
0,3351.0,206,27.0,726,124,3813.0,192,252,180,2271,...,0,0,0,0,0,1,0,0,1,1
1,2732.0,129,7.0,212,1,1082.0,231,236,137,912,...,0,0,0,0,0,0,0,0,2,1
2,2572.0,24,9.0,201,25,957.0,216,222,142,2191,...,0,0,0,0,0,0,0,0,2,1
3,2824.0,69,13.0,417,39,3223.0,233,214,110,6478,...,0,0,0,0,0,0,0,0,2,1
4,NaN,84,NaN,120,9,NaN,227,231,139,4983,...,0,0,0,0,0,0,0,0,2,1

In [ ]:
df.shape

(51000, 56)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Elevation                           47500 non-null  float64
 1   Aspect                              51000 non-null  int64
 2   Slope                               47500 non-null  float64
 3   Horizontal_Distance_To_Hydrology    51000 non-null  int64
 4   Vertical_Distance_To_Hydrology      51000 non-null  int64
 5   Horizontal_Distance_To_Roadways     47500 non-null  float64
 6   Hillshade_9am                       51000 non-null  int64
 7   Hillshade_Noon                      51000 non-null  int64
 8   Hillshade_3pm                       51000 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  51000 non-null  int64
 10  Wilderness_Area1                    51000 non-null  int64
 11  Wilderness_Area2                    51000 non-null  int64
 12  Wilderness_Area3                    51000 non-null  int64
 13  Wilderness_Area4                    51000 non-null  int64
 14  Soil_Type1                          51000 non-null  int64
 15  Soil_Type2                          51000 non-null  int64
 16  Soil_Type3                          51000 non-null  int64
 17  Soil_Type4                          51000 non-null  int64
 18  Soil_Type5                          51000 non-null  int64
 19  Soil_Type6                          51000 non-null  int64
 20  Soil_Type7                          51000 non-null  int64
 21  Soil_Type8                          51000 non-null  int64
 22  Soil_Type9                          51000 non-null  int64
 23  Soil_Type10                         51000 non-null  int64
 24  Soil_Type11                         51000 non-null  int64
 25  Soil_Type12                         51000 non-null  int64
 26  Soil_Type13                         51000 non-null  int64
 27  Soil_Type14                         51000 non-null  int64
 28  Soil_Type15                         51000 non-null  int64
 29  Soil_Type16                         51000 non-null  int64
 30  Soil_Type17                         51000 non-null  int64
 31  Soil_Type18                         51000 non-null  int64
 32  Soil_Type19                         51000 non-null  int64
 33  Soil_Type20                         51000 non-null  int64
 34  Soil_Type21                         51000 non-null  int64
 35  Soil_Type22                         51000 non-null  int64
 36  Soil_Type23                         51000 non-null  int64
 37  Soil_Type24                         51000 non-null  int64
 38  Soil_Type25                         51000 non-null  int64
 39  Soil_Type26                         51000 non-null  int64
 40  Soil_Type27                         51000 non-null  int64
 41  Soil_Type28                         51000 non-null  int64
 42  Soil_Type29                         51000 non-null  int64
 43  Soil_Type30                         51000 non-null  int64
 44  Soil_Type31                         51000 non-null  int64
 45  Soil_Type32                         51000 non-null  int64
 46  Soil_Type33                         51000 non-null  int64
 47  Soil_Type34                         51000 non-null  int64
 48  Soil_Type35                         51000 non-null  int64
 49  Soil_Type36                         51000 non-null  int64
 50  Soil_Type37                         51000 non-null  int64
 51  Soil_Type38                         51000 non-null  int64
 52  Soil_Type39                         51000 non-null  int64
 53  Soil_Type40                         51000 non-null  int64
 54  Cover_Type                          51000 non-null  int64
 55  Soil_Sum                            51000 non-null  int64
dtypes: float64(3), int64(53)
memory usage: 21.8 MB

In [ ]:
df.describe()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type,Soil_Sum
count,47500.000000,51000.000000,47500.000000,51000.000000,51000.000000,47500.000000,51000.000000,51000.000000,51000.000000,51000.000000,...,51000.000000,51000.000000,51000.000000,51000.000000,51000.000000,51000.000000,51000.000000,51000.000000,51000.000000,51000.000000
mean,3021.581495,155.957137,14.649726,270.239725,46.295863,2354.933663,212.251647,223.394333,142.493725,1984.120725,...,0.077608,0.002804,0.002882,0.000137,0.000490,0.026647,0.023490,0.015588,2.041176,1.029667
std,658.517815,111.937969,9.878553,212.383104,58.216221,1561.899614,26.637251,19.709316,38.400429,1322.853412,...,0.267556,0.052878,0.053611,0.011715,0.022135,0.161051,0.151456,0.123877,1.388845,0.295728
min,1871.000000,0.000000,0.000000,0.000000,-173.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,2813.000000,59.000000,9.000000,108.000000,7.000000,1107.000000,198.000000,213.000000,119.000000,1022.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,3001.000000,127.000000,13.000000,218.000000,30.000000,2010.000000,218.000000,226.000000,143.000000,1714.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000
75%,3170.000000,261.000000,19.000000,390.000000,69.000000,3332.000000,231.000000,237.000000,169.000000,2556.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000
max,10845.000000,360.000000,195.000000,1361.000000,597.000000,7087.000000,254.000000,254.000000,253.000000,7145.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000,4.000000

In [ ]:
df.isnull().sum()

Elevation                             3500
Aspect                                   0
Slope                                 3500
Horizontal_Distance_To_Hydrology         0
Vertical_Distance_To_Hydrology           0
Horizontal_Distance_To_Roadways       3500
Hillshade_9am                            0
Hillshade_Noon                           0
Hillshade_3pm                            0
Horizontal_Distance_To_Fire_Points       0
Wilderness_Area1                         0
Wilderness_Area2                         0
Wilderness_Area3                         0
Wilderness_Area4                         0
Soil_Type1                               0
Soil_Type2                               0
Soil_Type3                               0
Soil_Type4                               0
Soil_Type5                               0
Soil_Type6                               0
Soil_Type7                               0
Soil_Type8                               0
Soil_Type9                               0
Soil_Type10                              0
Soil_Type11                              0
Soil_Type12                              0
Soil_Type13                              0
Soil_Type14                              0
Soil_Type15                              0
Soil_Type16                              0
Soil_Type17                              0
Soil_Type18                              0
Soil_Type19                              0
Soil_Type20                              0
Soil_Type21                              0
Soil_Type22                              0
Soil_Type23                              0
Soil_Type24                              0
Soil_Type25                              0
Soil_Type26                              0
Soil_Type27                              0
Soil_Type28                              0
Soil_Type29                              0
Soil_Type30                              0
Soil_Type31                              0
Soil_Type32                              0
Soil_Type33                              0
Soil_Type34                              0
Soil_Type35                              0
Soil_Type36                              0
Soil_Type37                              0
Soil_Type38                              0
Soil_Type39                              0
Soil_Type40                              0
Cover_Type                               0
Soil_Sum                                 0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(952)

In [ ]:
soil_cols = [col for col in df.columns if "Soil_Type" in col]

df['Soil_Sum'] = df[soil_cols].sum(axis=1)
df['Soil_Sum'].value_counts()

Soil_Sum
1    50490
4      493
3       17
Name: count, dtype: int64

## STEP 4: Fix Missing Values

In [ ]:
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_1139/4258971048.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

## STEP 5: Remove Duplicates

In [ ]:
df = df.drop_duplicates()

## STEP 6: Handle Outliers

In [ ]:
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[col] >= lower) & (df[col] <= upper)]

In [ ]:
cols = ['Elevation', 'Slope', 'Horizontal_Distance_To_Roadways']

for col in cols:
    df = remove_outliers(df, col)

## STEP 7: Fix Validation Errors

In [ ]:
def fix_one_hot(row):
    if row[soil_cols].sum() != 1:
        max_col = row[soil_cols].idxmax()
        row[soil_cols] = 0
        row[max_col] = 1
    return row

df = df.apply(fix_one_hot, axis=1)

## STEP 8: Verify Everything

In [ ]:
df.isnull().sum()

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0
Soil_Type12                           0
Soil_Type13                           0
Soil_Type14                           0
Soil_Type15                           0
Soil_Type16                           0
Soil_Type17                           0
Soil_Type18                           0
Soil_Type19                           0
Soil_Type20                           0
Soil_Type21                           0
Soil_Type22                           0
Soil_Type23                           0
Soil_Type24                           0
Soil_Type25                           0
Soil_Type26                           0
Soil_Type27                           0
Soil_Type28                           0
Soil_Type29                           0
Soil_Type30                           0
Soil_Type31                           0
Soil_Type32                           0
Soil_Type33                           0
Soil_Type34                           0
Soil_Type35                           0
Soil_Type36                           0
Soil_Type37                           0
Soil_Type38                           0
Soil_Type39                           0
Soil_Type40                           0
Cover_Type                            0
Soil_Sum                              0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Soil_Sum'] = df[soil_cols].sum(axis=1)
df['Soil_Sum'].value_counts()

Soil_Sum
1.0    46505
Name: count, dtype: int64

## STEP 9: Save Clean Dataset

In [ ]:
df.head(10)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type,Soil_Sum
0,3351.0,206.0,27.0,726.0,124.0,3813.0,192.0,252.0,180.0,2271.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,2732.0,129.0,7.0,212.0,1.0,1082.0,231.0,236.0,137.0,912.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
2,2572.0,24.0,9.0,201.0,25.0,957.0,216.0,222.0,142.0,2191.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,2824.0,69.0,13.0,417.0,39.0,3223.0,233.0,214.0,110.0,6478.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
4,3001.0,84.0,13.0,120.0,9.0,2010.0,227.0,231.0,139.0,4983.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
6,3004.0,236.0,5.0,960.0,95.0,5814.0,211.0,244.0,171.0,5713.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
7,3232.0,111.0,10.0,541.0,78.0,1342.0,237.0,229.0,122.0,2270.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
8,3141.0,156.0,6.0,503.0,72.0,240.0,228.0,241.0,147.0,1354.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
9,2524.0,36.0,7.0,30.0,3.0,630.0,220.0,225.0,141.0,300.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
10,2860.0,156.0,15.0,228.0,98.0,3961.0,236.0,241.0,131.0,5433.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0

In [ ]:
df.to_csv("forest_cleaned_dataset.csv", index=False)

In [ ]:
# Download
from google.colab import files
files.download("forest_cleaned_dataset.csv")